<a href="https://colab.research.google.com/github/bhosalesahana-art/EXCEL-2026/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [120]:
import numpy as np
print("=====STUDENT ANALYSIS USING NUMPY====\n")
#1.Dataset Creation(with missing values)
marks=np.array([[78,85,90],[88,76,np.nan],[67,70,80],[90,95,88],[np.nan,60,75]])
subjects=["Math","Science","English"]
print("Original Marks Data:\n",marks,"\n")


=====STUDENT ANALYSIS USING NUMPY====

Original Marks Data:
 [[78. 85. 90.]
 [88. 76. nan]
 [67. 70. 80.]
 [90. 95. 88.]
 [nan 60. 75.]] 



In [107]:
# 2 Array Properties
print("Array Shape:",marks.shape)
print("Array Dimensions:",marks.ndim)
print("Total Elements:",marks.size)
print("Data type:",marks.dtype,"\n")

Array Shape: (5, 3)
Array Dimensions: 2
Total Elements: 15
Data type: float64 



In [126]:
#3 Handling Missing values
subject_mean=np.nanmean(marks,axis=0)
missing_indices=np.where(np.isnan(marks))
marks[missing_indices]=np.take(subject_mean,missing_indices[1])
print("Marks after handling missing values:\n",marks,"\n")


Marks after handling missing values:
 [[78.   85.   90.  ]
 [88.   76.   83.25]
 [67.   70.   80.  ]
 [90.   95.   88.  ]
 [80.75 60.   75.  ]] 



In [127]:
# 4 indexing & Slicing
print("Math marks:",marks[:,0])
print("Marks of student2:",marks[1],"\n")


Math marks: [78.   88.   67.   90.   80.75]
Marks of student2: [88.   76.   83.25] 

[]


In [110]:
# 5 BoardCasting(Adding Bonus Marks)
bonus_marks=marks+5
print("Marks after adding bouns:\n",bonus_marks,"\n")

Marks after adding bouns:
 [[ 83.    90.    95.  ]
 [ 93.    81.    88.25]
 [ 72.    75.    85.  ]
 [ 95.   100.    93.  ]
 [ 85.75  65.    80.  ]] 



In [111]:
# 6 Statistical Analysis
student_avg=marks.mean(axis=1)
subject_avg=marks.mean(axis=0)
print("Student-wise Average Marks:",student_avg)
print("Subject-wise Average Marks:")
for i in range(len(subjects)):
  print(subjects[i],":",subject_avg[i])
print()

Student-wise Average Marks: [84.33333333 82.41666667 72.33333333 91.         71.91666667]
Subject-wise Average Marks:
Math : 80.75
Science : 77.2
English : 83.25



In [112]:
# 7 Performance Metrics
print("Highest Score:",marks.max())
print("Lowest Score:",marks.min())
print("Standard Deviation:",marks.std(),"\n")

Highest Score: 95.0
Lowest Score: 60.0
Standard Deviation: 9.312088917101253 



In [113]:
# 8 Ranking Students
ranking=np.argsort(student_avg)[::-1]
print("Student Ranking(Top to Bottom):")
for i,rank in enumerate(ranking):
  print(f"Rank{i+1}->Student{rank+1}")
print()


Student Ranking(Top to Bottom):
Rank1->Student4
Rank2->Student1
Rank3->Student2
Rank4->Student3
Rank5->Student5



In [114]:
# 9 Boolean Indexing(top performers)
top_students=student_avg>85
print("Top Performing Students(Avg>85):",top_students)
print("Student Nummbers:",np.where(top_students)[0]+1,"\n")

Top Performing Students(Avg>85): [False False False  True False]
Student Nummbers: [4] 



In [115]:
# 10 Shape Manipulation
flat_marks=marks.flatten()
print("Flattened Marks Data:",flat_marks,"\n")

Flattened Marks Data: [78.   85.   90.   88.   76.   83.25 67.   70.   80.   90.   95.   88.
 80.75 60.   75.  ] 



In [116]:
#11 Sorting &Searching
sorted_marks=np.sort(flat_marks)
print("Sorted Marks:",sorted_marks)
print("Unique Marks:",np.unique(sorted_marks),"\n")

Sorted Marks: [60.   67.   70.   75.   76.   78.   80.   80.75 83.25 85.   88.   88.
 90.   90.   95.  ]
Unique Marks: [60.   67.   70.   75.   76.   78.   80.   80.75 83.25 85.   88.   90.
 95.  ] 



In [117]:
#12 Random Data Simulation
np.random.seed(10)
random_scores=np.random.randint(60,100,size=(5,3))
print("Randomly Generated Scores:\n",random_scores,"\n")


Randomly Generated Scores:
 [[69 96 75]
 [60 88 85]
 [89 89 68]
 [69 60 96]
 [76 96 71]] 



In [118]:
#13 Linear Algebra(Total Score Calclution)
weights=np.array([1,1,1])
total_scores=np.dot(marks,weights)
print("Total Scores of Students:",total_scores,"\n")

Total Scores of Students: [253.   247.25 217.   273.   215.75] 



In [119]:
#14 Performance Comparison(list vs Numpy)
python_list=[1,2,3,4,5]
numpy_array=np.array(python_list)
print("Python List*2:",[x*2 for x in python_list])
print("Numpy Array*2:",numpy_array*2)

Python List*2: [2, 4, 6, 8, 10]
Numpy Array*2: [ 2  4  6  8 10]
